### ISSUE TITLE
Subnets on JDBCs databases

### ISSUE THREAD

**Issue by sjlva** [GoogleCloudPlatform/dataproc-templates#245]
Hi, I'm trying to access some JDBC databases from the template JDBCTOGCS. But it always returns me an connection error. I think it is because of my subnet (I'm using a default one in us-central1 with private Google access).

The problem is that I can't access public databases, like ones in `relational.fit.cvut.cz` on port 3306. How should I approach that? 

That is the error: 
```bash
Exception in thread "main" com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

How can I enable a subnet firewall to accept port 3306?

**Comment by shashank-google** [comment]
Hi @sjlva 
Thanks for reaching out.
Serverless Dataproc spins up (ephemeral) VM on your GCP VPC and therefore will have access to anything on internet unless your org policy blocks it.

I ran below command and I was able to export data out.
```
export GCP_PROJECT=shashank-data-eng \
export REGION=us-central1  \
export SUBNET=projects/shashank-data-eng/regions/us-central1/subnetworks/default   \
export GCS_STAGING_LOCATION=gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb \
export JARS=gs://shashank-data-eng/dataproc-templates/jdbc2gcs/jar/mysql-connector-java-8.0.28.jar

bin/start.sh \
-- --template JDBCTOGCS \
--templateProperty 'jdbctogcs.jdbc.url=jdbc:mysql://relational.fit.cvut.cz:3306/financial?user=guest&password=relational' \
--templateProperty jdbctogcs.jdbc.driver.class.name=com.mysql.cj.jdbc.Driver \
--templateProperty jdbctogcs.output.location=gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb/client_export \
--templateProperty jdbctogcs.output.format=avro \
--templateProperty jdbctogcs.write.mode=OVERWRITE \
--templateProperty 'jdbctogcs.sql=SELECT * FROM financial.client'
```

Please ack if similar works for you or not ?
Reach out to dataproc-templates-support-external@googlegroups.com if you have more questions.

**Comment by sjlva** [comment]
Hi @shashank-google, thanks for your reply.

But it does not work for me. I think it is probably an VPC error, how should I configure a default VPC to work properly? I already enabled the Private Google Access. 

I run the same command you mentioned (just changed the env variables to suit my ones, and using the mysql-connector-java-8.0.30.jar instead).

I get the following error message:

```bash
Exception in thread "main" com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at org.apache.spark.sql.execution.datasources.jdbc.connection.BasicConnectionProvider.getConnection(BasicConnectionProvider.scala:49)
	at org.apache.spark.sql.execution.datasources.jdbc.connection.ConnectionProvider$.create(ConnectionProvider.scala:77)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$createConnectionFactory$1(JdbcUtils.scala:64)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.getQueryOutputSchema(JDBCRDD.scala:62)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:57)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:239)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:36)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
	at com.google.cloud.dataproc.templates.jdbc.JDBCToGCS.runTemplate(JDBCToGCS.java:66)
	at com.google.cloud.dataproc.templates.main.DataProcTemplate.runSparkJob(DataProcTemplate.java:187)
	at com.google.cloud.dataproc.templates.main.DataProcTemplate.main(DataProcTemplate.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
	... 31 more
Caused by: java.net.SocketException: Network is unreachable (connect failed)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 34 more
```

**Comment by shashank-google** [comment]
This is not dataproc template issue, so at this point it is beyond our scope.
Btw, it is not about private google access, as this mysql is hosted on public Internet.

To debug you can create a vm manually on your vpc and verify if mysql cli client is able to connect (or you are able to telnet host and port). If that works then ideally spark vms launched by dp serverless will also work.

**Comment by shashank-google** [comment]
@sjlva bumping up to check if you were able to debug it.

**Comment by sjlva** [comment]
@shashank-google I created a vm, in the us-central1 default network. It runs fine:

```bash
mysql -u guest -prelational -h relational.fit.cvut.cz -P 3306 financial -p
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 50204
Server version: 5.5.5-10.3.15-MariaDB-log MariaDB Server

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT * FROM financial.client LIMIT 5;
+-----------+--------+------------+-------------+
| client_id | gender | birth_date | district_id |
+-----------+--------+------------+-------------+
|         1 | F      | 1970-12-13 |          18 |
|         2 | M      | 1945-02-04 |           1 |
|         3 | F      | 1940-10-09 |           1 |
|         4 | M      | 1956-12-01 |           5 |
|         5 | F      | 1960-07-03 |           5 |
+-----------+--------+------------+-------------+
5 rows in set (0.12 sec)

mysql> 
```

At this moment, I'm running those templates in a dataproc cluster with the command ```gcloud dataproc jobs submit pyspark``` because dataproc serverless is failing.

Do you have some step by step network configuration to use dataproc? I followed this https://cloud.google.com/dataproc-serverless/docs/concepts/network, I also tried the default one with Private Google Access enabled. I got no success.

I really can't figure out why It's not running. Why can I run the templates in a dataproc cluster, but I can't in dataproc serverless?

**Comment by shashank-google** [comment]
I think I got it.
You will need to create Cloud NAT (for the subnet / region you are passing to dataproc) as mentioned: https://cloud.google.com/dataproc-serverless/docs/concepts/network
LMK if it works after that.

**Comment by sjlva** [comment]
Thank you @shashank-google!
I created a Cloud NAT and it worked!
