### ISSUE TITLE
[shell script] Job fails when gcs staging location has trailing forward slash "/"

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#250]
Tested with java's JDBCToGCS template.
Job fails when gcs path ends with forward slash like below:
```
export GCS_STAGING_LOCATION=gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb/
```

Example error log:
```
gcloud beta dataproc batches submit spark --project=shashank-data-eng --region=us-central1 --jars=file:///usr/lib/spark/external/spark-avro.jar,gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb//grpc-grpclb-1.40.1.jar,gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb//dataproc-templates-1.0-SNAPSHOT.jar,gs://shashank-data-eng/dataproc-templates/jdbc2gcs/jar/mysql-connector-java-8.0.28.jar --labels=job_type=dataproc_template --deps-bucket=gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb/ --files=gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb//log4j-spark-driver-template.properties --properties=spark.driver.extraJavaOptions=-Dlog4j.configuration=file:log4j-spark-driver-template.properties --class=com.google.cloud.dataproc.templates.main.DataProcTemplate --subnet=projects/shashank-data-eng/regions/us-central1/subnetworks/default -- --template JDBCTOGCS --templateProperty jdbctogcs.jdbc.url=jdbc:mysql://relational.fit.cvut.cz:3306/financial?user=guest&password=relational --templateProperty jdbctogcs.jdbc.driver.class.name=com.mysql.cj.jdbc.Driver --templateProperty jdbctogcs.output.location=gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb/client_export --templateProperty jdbctogcs.output.format=avro --templateProperty jdbctogcs.write.mode=OVERWRITE --templateProperty jdbctogcs.sql=SELECT * FROM financial.client
Batch [3c8b45409b684e2389faed80e1ad5129] submitted.
=========== Cloud Dataproc Agent Error ===========
java.io.FileNotFoundException: File not found: gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb/grpc-grpclb-1.40.1.jar
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getFileStatus(GoogleHadoopFileSystemBase.java:958)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:389)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:340)
        at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2548)
        at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2517)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.copyToLocalFile(GoogleHadoopFileSystemBase.java:1614)
        at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2493)
        at com.google.cloud.hadoop.services.agent.util.HadoopUtil.download(HadoopUtil.java:127)
        at com.google.cloud.hadoop.services.agent.job.handler.AbstractJobHandler.downloadResources(AbstractJobHandler.java:568)
        at com.google.cloud.hadoop.services.agent.job.handler.AbstractJobHandler.prepareDriver(AbstractJobHandler.java:834)
        at com.google.cloud.hadoop.services.repackaged.com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.cloud.hadoop.services.repackaged.com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.cloud.hadoop.services.repackaged.com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
======== End of Cloud Dataproc Agent Error ========
ERROR: (gcloud.beta.dataproc.batches.submit.spark) Batch job is FAILED. Detail: File not found: gs://shashank-data-eng/dataproc-templates/jdbc2gcs/publicdb/grpc-grpclb-1.40.1.jar.
Running auto diagnostics on the batch. It may take few minutes before diagnostics output is available. Please check diagnostics output by running 'gcloud dataproc batches describe' command.
```

Needs to be fixed such that job joes not results into error with or without forward slash in the end.
Needs to be verified for python too.

**Comment by vanshaj-bhatia** [comment]
@shashank-google Apparently it was a bug with Python templates as well. Fixed and tested couple of templates for both Java & Python. Please review.
