### ISSUE TITLE
[QUESTION] Unable to resolve mariadb/mysql jdbc driver class from gke cluster

### ISSUE THREAD

**Issue by cghislai** [GoogleCloudPlatform/dataproc-templates#804]
Im trying to run a spark job using the template jdbcToBigQuery on a dedicated cluster in gke, but i have trouble putting the mariadb jdbc driver on the classpath of the spark job instance. 

This cause the job to fail with an error ` java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver`.

I create the cluster using the following command:
```
gcloud dataproc clusters gke create --project=GCP_PROJECT_ID --gke-cluster=GKE_CLUSTER_NAME --gke-cluster-location=europe-west1-d --spark-engine-version=dataproc-2.0 --staging-bucket=dataproc_jobs_source --pools=name=dataproc,roles=default,min=0,max=4,machineType=e2-medium --setup-workload-identity --namespace=dataproc DATAPROC_CLUSTER_NAME --region=europe-west1

Waiting on operation [projects/GCP_PROJECT_ID/regions/europe-west1/operations/4fc5a189-f5b0-39ac-8b68-71ec16a6adf9].
Waiting for cluster creation operation...
...................................................................................................................................................................................................................................................................................................................................................................done.
Created [https://dataproc.googleapis.com/v1/projects/GCP_PROJECT_ID/regions/europe-west1/clusters/DATAPROC_CLUSTER_NAME] Virtual Cluster created on GKE cluster: projects/GCP_PROJECT_ID/locations/europe-west1-d/clusters/GKE_CLUSTER_NAME.
```

I compiled the repository java templates and put the shaded jar in the cloud storage bucket, to work around apache commons cli issue. I also download the mariadb driver and put it in that bucket as well. I then launch the job instance using the following command:

```
gcloud dataproc jobs submit spark --project=GCP_PROJECT_ID--region=europe-west1 --jars=file:///usr/lib/spark/external/spark-avro.jar,gs://dataproc_jobs_source/deps/mariadb-java-client-3.1.4.jar,gs://dataproc_jobs_source/jobs/dataproc-templates-1.0-SNAPSHOT.jar --files=gs://dataproc_jobs_source/deps/mariadb-java-client-3.1.4.jar --properties=spark.driver.extraClassPath=mariadb-java-client-3.1.4.jar,spark.executor.extraClassPath=mariadb-java-client-3.1.4.jar --labels=job_type=dataproc_template,jenkins_job_name=dataproc_template_jdbc2bigquery,jenkins_build_number=69 --class=com.google.cloud.dataproc.templates.main.DataProcTemplate --cluster=DATAPROC_CLUSTER_NAME --driver-log-levels=root=DEBUG -- --template JDBCTOBIGQUERY --templateProperty log.level=ALL --templateProperty project.id=GCP_PROJECT_ID --templateProperty jdbctobq.bigquery.location=BQ_LOCATION --templateProperty jdbctobq.jdbc.url=jdbc:mariadb://K8S_SERVICE_CN.svc.cluster.local:3306/nitro?user=USER&password=PASSWORD --templateProperty jdbctobq.jdbc.driver.class.name=org.mariadb.jdbc.Driver --templateProperty jdbctobq.sql.file=gs://dataproc_jobs_source/jobs/sql_input/INPUT_SQL_FILE.sql --templateProperty jdbctobq.write.mode=Overwrite --templateProperty jdbctobq.temp.gcs.bucket=gs://dataproc_jobs_source

Job [34ea6a61b97e43d79e3abd9ce0a52c0a] submitted.
```

Then in the log output, i get the error stack. I include the relevant bit below:

```
...
23/06/02 13:12:14 INFO org.apache.hadoop.hive.conf.HiveConf: Found configuration file null
23/06/02 13:12:14 INFO org.apache.spark.SparkContext: Running Spark version 3.1.3
23/06/02 13:12:14 INFO org.apache.spark.resource.ResourceUtils: ==============================================================
23/06/02 13:12:14 INFO org.apache.spark.resource.ResourceUtils: No custom resources configured for spark.driver.
23/06/02 13:12:14 INFO org.apache.spark.resource.ResourceUtils: ==============================================================
23/06/02 13:12:14 INFO org.apache.spark.SparkContext: Submitted application: Spark JDBCToBigQuery Job
...
23/06/02 13:12:17 INFO org.apache.spark.ui.SparkUI: Bound SparkUI to 0.0.0.0, and started at http://dp-spark-16778736-8df7-3b83-8b15-305c3987706c-driver.dataproc.svc.cluster.local:4040/
23/06/02 13:12:17 INFO org.apache.spark.SparkContext: Added JAR file:///usr/lib/spark/external/spark-avro.jar at spark://dp-spark-16778736-8df7-3b83-8b15-305c3987706c-driver.dataproc.svc.cluster.local:22446/jars/spark-avro.jar with timestamp 1685711534416
23/06/02 13:12:17 INFO org.apache.spark.SparkContext: Added JAR gs://dataproc_jobs_source/deps/mariadb-java-client-3.1.4.jar at gs://dataproc_jobs_source/deps/mariadb-java-client-3.1.4.jar with timestamp 1685711534416
23/06/02 13:12:17 INFO org.apache.spark.SparkContext: Added JAR gs://dataproc_jobs_source/jobs/dataproc-templates-1.0-SNAPSHOT.jar at gs://dataproc_jobs_source/jobs/dataproc-templates-1.0-SNAPSHOT.jar with timestamp 1685711534416
23/06/02 13:12:17 INFO org.apache.spark.SparkContext: Added JAR local:///usr/lib/hadoop/hadoop-common.jar at file:/usr/lib/hadoop/hadoop-common.jar with timestamp 1685711534416
23/06/02 13:12:17 INFO org.apache.spark.SparkContext: Added file gs://dataproc_jobs_source/deps/mariadb-java-client-3.1.4.jar at gs://dataproc_jobs_source/deps/mariadb-java-client-3.1.4.jar with timestamp 1685711534416
23/06/02 13:12:17 INFO org.apache.spark.util.Utils: Fetching gs://dataproc_jobs_source/deps/mariadb-java-client-3.1.4.jar to /var/data/spark-845ecc57-ae72-4141-bfcb-14ace80700bd/spark-6c608084-729a-4332-b95d-a0888ece1758/userFiles-3ea72c21-4dd0-434b-bf17-f51e3457430d/fetchFileTemp7595938043739943085.tmp
...
Exception in thread "main" java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:102)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:102)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:102)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:38)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:32)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:355)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:307)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:307)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:225)
	at com.google.cloud.dataproc.templates.jdbc.JDBCToBigQuery.validateInput(JDBCToBigQuery.java:218)
```

The documentation at https://github.com/GoogleCloudPlatform/dataproc-templates/tree/main/java/src/main/java/com/google/cloud/dataproc/templates/jdbc mentions mariadb as supported, but only provides details for the mysql connector. 
I followed similar steps to get the mariadb connector:
- download the jar from https://mariadb.com/kb/en/about-mariadb-connector-j/
- utilize the driver class name `org.mariadb.jdbc.Driver`.
- utilize the jdbc scheme `jdbc:mariadb:`
I also tried the mysql connector which produces the same error: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver

Spark documentation mentions the need to use a separate flag/property `--driver-class-path` pointing to the jdbc driver jar, in addition to the `--jars` parameter (see https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html).
I also see that, for their runtime environement configuration, they mention that `spark.driver.extraClassPath` should not be called from within the code, but put on the classpath using the cmd line argument or the default config file. (see https://spark.apache.org/docs/latest/configuration.html#runtime-environment). I tried to pass this as a `--property` argument to `gcloud dataproc job spark` command, but im not sure how it is forwarded to the spark instance.

Is there something missing in the documentation, or is it a limitation of the gke clusters, or am i missing something else?

**Comment by surjits254** [comment]
Hi cghislai,
The templates work for dataproc serverless where it reads jars from GCS and adds to appropriate location during job launch.
For cluster based execution you can try adding jar to /usr/lib/spark/jars/ and run you job. From the logs you shared Jar is fetched from GCS but Job cannot find it.
Let me know if this helps.

**Comment by cghislai** [comment]
Thanks.

Unfortunately, as we moved to an alternative solution and removed the related serverless apis, im unable to test this further ,so i will close this issue.
